### PR TITLE
Fixes implicit declaration of function ngx_http_upstream_check_add_peer

### PR DESCRIPTION
**Pull request by jaygooby**
Fixes implicit declaration of function 'ngx_http_upstream_check_add_peer' when compiling with nginx_upstream_check_module

### CODE REVIEW

**Comment by itoffshore** [comment]
Many thanks for the `PR` Jay

**Comment by jaygooby** [comment]
@itoffshore I'm hoping to get the upstream fair's score showing on the nginx_upstream_check_module status page if you're using both modules. As a first stab, I've just hooked up the busyness and access_count...

https://github.com/yaoweibin/nginx_upstream_check_module/issues/156

Any idea what the busyness represents?

**Comment by itoffshore** [comment]
we don't have that module in Alpine & I've never used it before

https://github.com/yaoweibin/nginx_upstream_check_module/blob/94e76ec66e99924ab479079745dd05b5cf184e35/ngx_http_upstream_check_module.c

`busyness` seems to increment by one `++` for every peer available & decrement by one `--` for each peer that is free

**Comment by jaygooby** [comment]
Thanks! That's definitely not what I thought it was. Time for me to read some nginx internals :)

**Pull request merged**
